### ISSUE TITLE
Upload authorities list

### ISSUE THREAD

**Issue by schlos** [codeforcroatia/alaveteli#24]
Upload latest authorities list

**Comment by schlos** [comment]
Ažurirani popis sa stanjem na dan 10. travnja 2015. sadrži podatke o 5.724 tijela javne vlasti, u odnosu na koje postoje podaci o 3583 službenika za informiranje.

http://www.pristupinfo.hr/wp-content/uploads/2015/04/TJV-100415-za-web1.xls

**Comment by schlos** [comment]
CSV converter used is http://www.convertcsv.com/csv-to-csv.htm

**Comment by hrcone** [comment]
molim maknite me iz cca.

hvala

2015-04-26 1:45 GMT+02:00 Miroslav <notifications@github.com>:

**Comment by schlos** [comment]
Done, total 5717 public bodies.
