### ISSUE TITLE
Apache2 not installed problem

### ISSUE THREAD

**Issue by schlos** [codeforcroatia/alaveteli#5]
Cron <root@imamopravoznati> /var/www/imamopravoznati/alaveteli/commonlib/bin/run-with-lockfile.sh -n /var/www/imamopravoznati/change-xapian-database.lock "/var/www/imamopravoznati/alaveteli/script/compact-xapian-database production" || echo "stalled?"

```
commonlib/bin/output-on-error: 51: commonlib/bin/output-on-error: /etc/init.d/apache2: not found
stalled?
```

**Comment by schlos** [comment]
Thanks to Louise for info:
This is a known issue - here's the ticket (https://github.com/mysociety/alaveteli/issues/2165)

Temporary solution - just switch this script off from the cron file (comment it out).

**Comment by garethrees** [comment]
This should be fixed in the next release of Alaveteli (https://github.com/mysociety/alaveteli/pull/2171)

**Comment by schlos** [comment]
Problem last time occured:
date:	Sun, Jan 24, 2016 at 1:31 AM (UTC+1)

Upgraded to Alaveteli v0.23 around 12:PM, so this is under monitoring.

**Comment by schlos** [comment]
Closing as not reproducing anymore
